# This is a basic workflow to help you get started with Actions

name: GitHub Actions testiranje

on:
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run
  
  cypress2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run
  
  cypress3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run
          
  cypress4:
    runs-on: ubuntu-latest
    needs: [cypress,cypress2,cypress3]
    
    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run
          
  cypress5:
    runs-on: ubuntu-latest
    needs: [cypress,cypress2,cypress3]
    
    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run

  cypress6:
    runs-on: ubuntu-latest
    needs: [cypress,cypress2,cypress3]
    
    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run
    
  cypress7:
    runs-on: ubuntu-latest
    needs: [cypress,cypress2,cypress3]
    
    steps:
      - uses: actions/checkout@v2
               
      - name: Cypress test 
        run: | 
          cd src/frontend
          npx cypress run
