# This is a basic workflow to help you get started with Actions

name: GitHub Actions testiranje

on:
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up openJDK-15
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: 15

      - name: Build project
        run: mvn --file src/backend/pom.xml package -Dmaven.test.skip=true
        
    
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Testiranje cypress 
        run: |          
          docker-compose -d up
          cd src/frontend
          npx run cypress 
