# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: premakni in kopiraj
        run: cd src/backend
          

      # Runs a single command using the runners shell
      - name: Set up openJDK-15
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: 15

      - name: Build project
        run: mvn package -Dmaven.test.skip=true
        
      - name: izpisi 
        run: |
          ls -a
          cd target
          ls -a
